# Generated by Django 5.0.3 on 2024-04-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='img_rel_url',
            field=models.URLField(default='static/img/boost_images/1'),
        ),
    ]
