# Generated by Django 5.0.3 on 2024-04-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_core_api', '0002_boost_img_rel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='name',
            field=models.TextField(default='Кефир'),
        ),
    ]
