# Generated by Django 5.0.3 on 2024-04-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_core_api', '0003_boost_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='frame',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='core',
            name='frame_url',
            field=models.TextField(default='/static/img/click_images/frame0.png'),
        ),
        migrations.AlterField(
            model_name='boost',
            name='img_rel_url',
            field=models.URLField(default='None'),
        ),
        migrations.AlterField(
            model_name='boost',
            name='name',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='core',
            name='click_power',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='core',
            name='points_to_level_up',
            field=models.IntegerField(default=10),
        ),
    ]
