# Generated by Django 5.0.3 on 2024-04-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_clicker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
